blank_issues_enabled: false
contact_links:
  - name: Game Breaking Exploits
    url: https://discord.gg/ru-tgmc
    about: Securely disclose high priority issues to a member of the Maintainer Team here.
